[package]
name = "sqs-dispatch"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-sqs = "0.38.0"
aws-smithy-runtime-api = "0.101.0"
axum-server = { version = "0.6", features = ["tls-rustls"] }
tokio = { version = "1.20.1", features = ["full"] }
trait-variant = "0.1.2"

[dev-dependencies]
aws-config = "0.101.0"
ctor = "0.2.8"
mockall = "0.10.2"
