[package]
name = "sqs-dispatch"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-sqs = "0.38.0"
aws-smithy-runtime-api = "0.101.0"
axum-server = { version = "0.6", features = ["tls-rustls"] }
futures = "0.3"
tokio = { version = "1.20.1", features = ["full"] }
trait-variant = "0.1.2"
